### PR TITLE
Fixed ROS

### PR DESCRIPTION
**Pull request by 29antonioac**
ROS is working now. 

The problem was in the `fraction` variable: its meaning is different depending on `withReplacement` , see [the docs](https://spark.apache.org/docs/2.1.0/api/scala/index.html#org.apache.spark.rdd.RDD@sample(withReplacement:Boolean,fraction:Double,seed:Long):org.apache.spark.rdd.RDD[T]) . With `true` it models the **expected** number of times each value is taken. So the overRate input variable is enough to make it work!

A little test.

```
scala> val seq = sc.parallelize(1 to 10000)
seq: org.apache.spark.rdd.RDD[Int] = ParallelCollectionRDD[4] at parallelize at <console>:27
scala> seq.sample(true, 1.7, 1234).count()
res3: Long = 16958
scala>
```

Regards.

### CODE REVIEW

**Comment by saradelrio** [comment]
Dear analca3,

First of all, many thanks for trying to improve this implamentation for the ROS algorithm.

However, this implementation is already working properly. The problem is that you have not indicated the parameters correctly. 

In your example, the parameter that is received as overRate is 1.7. However, in the code you should use the value 170 as input parameter.

Of course the version you propose is also valid but it is another version of the implementation.

Sorry for the disturbances. I will try to give more details on how to execute the methods soon.

Best,

Sara

**Comment by 29antonioac** [comment]
What a mistake! I'm sorry for that :p .

Thank you for the explanation, now I can use this properly .

Best regards.

**Comment by saradelrio** [comment]
Hi again,

I just saw that your proposal is not correct. The following example shows the problem:

Actual ROS implementation:

overRate = 170
#positive instances = 10
#negative instances = 20
fraction = (num_neg*(overRate.toFloat/100)).toFloat/num_pos = 20 * (170/100) / 10 = 3.4
#final positive instances = 3.4 * 10 = 34
final overRate = 34 / 20 = 1.7 

Proposed ROS implementation:

overRate = 1.7
#positive instances = 10
#negative instances = 20
#final positive instances = 1.7 * 10 = 17
final overRate = 17 / 20 = 0.85 (is not correct)

Regards,

Sara

**Comment by 29antonioac** [comment]
Thank you! I understood that the overRate variable as the ratio new_negative_instances / negative_instances... Your explanation is very appreciated.

Best regards.

**Comment by saradelrio** [comment]
In fact, it is the ratio "number of final positive instances" / "number of negative instances".

If you have any questions do not hesitate to contact me.

Many thanks!
Sara

**Pull request closed without merging**
